src/main/java/br/com/caelum/ingresso/model/Carrinho.java
package br.com.caelum.ingresso.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Component;
import org.springframework.web.context.annotation.SessionScope;

@Component
@SessionScope
public class Carrinho {

	private List<Ingresso> ingressos = new ArrayList<>();
	
	public void add(Ingresso ingresso){
		ingressos.add(ingresso);
	}
	
	public boolean isSelecionado(Lugar lugar){
		return ingressos.stream().map(Ingresso::getLugar).anyMatch(l -> l.equals(lugar));
	}
	
	public Compra toCompra(){
		return new Compra(ingressos);
	}
	
	public BigDecimal getTotal(){
		return ingressos.stream().map(Ingresso::getPreco).reduce(BigDecimal::add).orElse(BigDecimal.ZERO);
	}

	public List<Ingresso> getIngressos() {
		return ingressos;
	}

	public void setIngressos(List<Ingresso> ingressos) {
		this.ingressos = ingressos;
	}
	
}

src/main/java/br/com/caelum/ingresso/model/Compra.java
package br.com.caelum.ingresso.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity
public class Compra {

	@Id
	@GeneratedValue
	private Long id;
	
	@OneToMany(cascade = CascadeType.PERSIST)
	List<Ingresso> ingressos = new ArrayList<>();
	
	/**
	 * @deprecated hibernate only
	 */
	public Compra(){
		
	}
	
	public Compra(List<Ingresso> ingressos){
		this.ingressos = ingressos;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public List<Ingresso> getIngressos() {
		return ingressos;
	}

	public void setIngressos(List<Ingresso> ingressos) {
		this.ingressos = ingressos;
	}
	
	
	
}

src/main/java/br/com/caelum/ingresso/model/TipoDeIngresso.java
package br.com.caelum.ingresso.model;

import java.math.BigDecimal;

import br.com.caelum.ingresso.model.descontos.Desconto;
import br.com.caelum.ingresso.model.descontos.DescontoParaBancos;
import br.com.caelum.ingresso.model.descontos.DescontoParaEstudantes;
import br.com.caelum.ingresso.model.descontos.SemDesconto;

public enum TipoDeIngresso {

	INTEIRO(new SemDesconto()),
	ESTUDANTE(new DescontoParaEstudantes()),
	BANCO(new DescontoParaBancos());
	
	private final Desconto desconto;
	
	TipoDeIngresso(Desconto desconto){
		this.desconto = desconto;
	}
	
	public BigDecimal aplicaDesconto(BigDecimal valor){
		return desconto.aplicarDescontoSobre(valor);
	}
	
	public String getDescricao(){
		return desconto.getDescricao();
	}
	
}

src/main/java/br/com/caelum/ingresso/controller/CompraController.java
package br.com.caelum.ingresso.controller;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.ModelAndView;

import br.com.caelum.ingresso.dao.CompraDao;
import br.com.caelum.ingresso.dao.LugarDao;
import br.com.caelum.ingresso.dao.SessaoDao;
import br.com.caelum.ingresso.model.Carrinho;
import br.com.caelum.ingresso.model.Cartao;
import br.com.caelum.ingresso.model.form.CarrinhoForm;

@Controller
public class CompraController {

	@Autowired
	private SessaoDao sessaoDao;
	
	@Autowired
	private LugarDao lugarDao;
	
	@Autowired
	private Carrinho carrinho;
	
	@Autowired
	private CompraDao compraDao;
	
	@PostMapping("/compra/ingressos")
	public ModelAndView enviarParaPagamento(CarrinhoForm carrinhoForm){
		ModelAndView modelAndView = new ModelAndView("redirect:/compra");
		
		carrinhoForm.toIngresso(sessaoDao, lugarDao).forEach(carrinho::add);
		
		return modelAndView;
	}
	
	@GetMapping("/compra")
	public ModelAndView checkout(Cartao cartao){
		ModelAndView modelAndView = new ModelAndView("compra/pagamento");
		
		modelAndView.addObject("carrinho", carrinho);
		return modelAndView;
	}
	
	@PostMapping
	@Transactional
	public ModelAndView comprar(@Valid Cartao cartao, BindingResult result){
		ModelAndView modelAndView = new ModelAndView("redirect:/");
		
		if(cartao.isValido()){
			compraDao.save(carrinho.toCompra());
		}else{
			result.rejectValue("vencimento", "Vencimento inválido");
			return checkout(cartao);
		}
		
		return modelAndView;
		
	}
	
}

src/main/webapp/WEB-INF/views/compra/compra.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib tagdir="/WEB-INF/tags/" prefix="ingresso"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<ingresso:template>
	<jsp:body>
		<div class=" col-md-6 col-md-offset-3">
		<c:forEach var="filme" items="${filmes}">

				<div class="col-md-4 ">
					<a href="/filme/${filme.id}/detalhe">
						<div class="panel panel-default panelSize">
							<div class="panel-heading text-center"><strong>${filme.nome}</strong></div>
							<div class="panel-body">
								<div>
									<strong>Genero:</strong> ${filme.genero}
								</div>
								<div>
									<strong>Duração:</strong> ${filme.duracao.toMinutes()} minutos
								</div>
							</div>
						</div>
					</a>
				</div>

		</c:forEach>
		</div>
    <style>
		a:hover {
			text-decoration: none;
		}

		.panel{
			transition: 		transform 0.7s;
		}

		.panel:hover{
			transform: 			translateY(-0.5em);
		}

		.panelSize {
			min-height: 10.5em;
			min-width: 13em;
		}
	</style>
    </jsp:body>
</ingresso:template>

src/main/webapp/WEB-INF/views/compra/lista.jsp
<%--
  Created by IntelliJ IDEA.
  User: nando
  Date: 07/02/17
  Time: 17:46
  To change this template use File | Settings | File Templates.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib tagdir="/WEB-INF/tags/" prefix="ingresso"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<ingresso:template>
    <jsp:body>
        <div class=" col-md-6 col-md-offset-3">
            <c:forEach items="${compras}" var="compra">
                <div>
                    <h3>${compra.id}</h3>

                    <table class="table table-hover">
                        <thead>
                            <th>Horario</th>
                            <th>Filme</th>
                            <th>Sala</th>
                            <th>Lugar</th>
                            <th>Tipo de Ingresso</th>
                            <th>Preço</th>
                        </thead>

                        <tbody>
                            <c:forEach items="${compra.ingressos}" var="ingresso">
                                <tr>
                                    <td>${ingresso.sessao.horario}</td>
                                    <td>${ingresso.sessao.filme.nome}</td>
                                    <td>${ingresso.sessao.sala.nome}</td>
                                    <td>${ingresso.lugar}</td>
                                    <td>${ingresso.tipoDeIngresso}</td>
                                    <td>${ingresso.preco}</td>
                                </tr>
                            </c:forEach>
                        </tbody>

                        <tfooter>
                            <tr>
                                <td colspan="5" class="text-right">Total</td>
                                <td>${compra.total}</td>
                            </tr>
                        </tfooter>

                    </table>

                </div>
            </c:forEach>
        </div>
    </jsp:body>
</ingresso:template>

src/main/webapp/WEB-INF/views/compra/pagamento.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib tagdir="/WEB-INF/tags/" prefix="ingresso" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<ingresso:template>
    <jsp:body>
   		<div class=" col-md-6 col-md-offset-3">
        <form action="/compra/comprar" method="post">
            <table class="table table-hover ">
                <thead>
                <th>Sala</th>
                <th>Lugar</th>
                <th>Filme</th>
                <th>Horario</th>
                <th>Tipo do Ingresso</th>
                <th>Preço</th>
                </thead>

                <tbody>
                <c:forEach items="${carrinho.ingressos}" var="ingresso" varStatus="status">

                    <input type="hidden" name="ingressos[${status.index}].sessao.id" value="${ingresso.sessao.id}">
                    <input type="hidden" name="ingressos[${status.index}].lugar.id" value="${ingresso.lugar.id}">
                    <input type="hidden" name="ingressos[${status.index}].tipoDeIngresso" value="${ingresso.tipoDeIngresso}">
                    <tr>
                        <td>${ingresso.sessao.sala.nome}</td>
                        <td>${ingresso.lugar.fileira}${ingresso.lugar.posicao}</td>
                        <td>${ingresso.sessao.filme.nome }</td>
                        <td>${ingresso.sessao.horario}</td>
                        <td>${ingresso.tipoDeIngresso.descricao}</td>
                        <td>${ingresso.preco}</td>
                    </tr>
                </c:forEach>
                </tbody>

                <tfoot>
                <td colspan="5" class="text-right"><strong>TOTAL</strong></td>
                <td><strong>${carrinho.total}</strong></td>
                </tfoot>

            </table>

            <div class="form-group">
                <div class="col-md-6">
                    <label for="nome">Nome:</label>
                    <input id="nome" type="text" name="nome" class="form-control">
                </div>

                <div class="col-md-6">
                    <label for="sobrenome">Sobrenome:</label>
                    <input id="sobrenome" type="text" name="sobrenome" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6">
                    <label for="cpf">CPF:</label>
                    <input id="cpf" type="text" name="cpf" class="form-control">
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-8">
                    <label for="cartaoDeCredito">Cartão de Crédito:</label>
                    <input id="cartaoDeCredito" type="text" name="cartaoDeCredito" class="form-control">
                </div>

                <div class="col-md-4">
                    <label for="cvv">CVV:</label>
                    <input id="cvv" type="text" name="cvv" class="form-control">
                </div>
            </div>

			<div class="form-group">
				<div class="col-md-6">
					<label for="vencimento">Vencimento:</label>
					<input id="vencimento" type="text" name="vencimento" class="form-control">
				</div>
			</div>

            <div class="form-group">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Comprar</button>
                </div>
            </div>

        </form>
		</div>
    </jsp:body>
</ingresso:template>